# version: '3.8'
services:
    # MongoDB
    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - "8081:8081"
        depends_on:
            - mongodb

    # flask
    app:  
        container_name: app
        build: .
        volumes:
            - ./app:/app  
        depends_on:
            - mongodb  
        ports:
            - "5001:5000"
        environment:
            # - FLASK_DEBUG=1
            - FLASK_APP=app.py
            - FLASK_ENV=development
        command: flask run -h 0.0.0.0
        restart: unless-stopped
        
volumes:
    mongodb_data: {}
