# version: '3.8'
services:

    neo4j:
        container_name: neo4j
        image: neo4j:4.4
        ports:
            - 7474:7474   # HTTP access (browser interface)
            - 7687:7687   # Bolt protocol (for applications)
        restart: unless-stopped
        environment:
            NEO4J_AUTH: neo4j/password
            NEO4J_USER: neo4j
            NEO4J_PASSWORD: password
        volumes:
            - neo4j_data:/data
            - neo4j_conf:/conf
            - neo4j_logs:/logs
            - neo4j_plugins:/plugins

    # flask
    app:  
        container_name: app
        build: .
        volumes:
            - ./app:/app  
        depends_on:
            - neo4j  
        ports:
            - "5001:5000"
        environment:
            FLASK_DEBUG: 1
            FLASK_APP: app.py
            FLASK_ENV: development
            # NEO4J_URI: bolt://neo4j:7687
            # NEO4J_USER: neo4j
            # NEO4J_PASSWORD: password
        command: flask run -h 0.0.0.0
        restart: unless-stopped
        
volumes:
    neo4j_data: {}
    neo4j_conf: {}
    neo4j_logs: {}
    neo4j_plugins: {}