# version: '3.8'
services:
    # database
    db:
        container_name: library_management_db
        image: postgres
        # hostname: localhost
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: library
        volumes: 
            - postgres-data:/var/lib/postgresql/data 
        restart: unless-stopped

    # admin2
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080

    # flask
    app:  
        container_name: app
        build: .
        volumes:
            - ./app:/app  
        depends_on:
            - db  
        ports:
            - "5001:5000"
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=app.py
            - FLASK_ENV=development
        command: flask run -h 0.0.0.0
        restart: unless-stopped
        
volumes:
    postgres-data: {}