# version: '3.8'
services:
    # database
    db:
        container_name: library_management_db
        image: postgres
        hostname: localhost
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: library
        volumes: 
            - postgres-data:/var/lib/postgresql/data 
        restart: unless-stopped

    # admin
    # pgadmin:
    #     container_name: container-pgadmin
    #     image: dpage/pgadmin4
    #     depends_on:
    #         - postgres
    #     ports: 
    #         - "5050:80"
    #     environment: 
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: root
    #     restart: unless-stopped

    # admin2
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080

    # flask
    app:  
        container_name: app
        build: .
        volumes:
            - .:/app
        depends_on:
            - db  
        ports:
            - "5001:5000"
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=app.py
            - FLASK_ENV=development
        restart: unless-stopped
        
volumes:
    postgres-data: {}